### ISSUE TITLE
Error downloading RW-HPS resfile

### ISSUE THREAD

**Issue by Av0idD4rk** [deng-rui/RW-HPS#1]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Can't download RW-HPS-ResFile@1.15_3.0.0_6 as the host is down

### Log files

[Log.txt](https://github.com/user-attachments/files/16714382/Log.txt)

**Comment by deng-rui** [comment]
CN : 开源已停止维护, 恢复无期
EN : Open Source has been discontinued, recovery is unlikely

**Comment by Av0idD4rk** [comment]
Thats' bad
