### ISSUE TITLE
玩家在游戏房间点击“开始游戏”后无法正常开始游戏

### ISSUE THREAD

**Issue by EdgeStar2020** [deng-rui/RW-HPS#57]
**描述错误**
玩家在游戏房间点击“开始游戏”后无法正常开始游戏

**截图**
![image](https://user-images.githubusercontent.com/58938653/113506827-a06cd300-9579-11eb-90a5-541d7816a72f.png)

**相关信息**
  -设备：阿里云服务器
  -操作系统：Ubuntu  20.04 64位
  -游戏版本：1.14h3
  -服务器版本：1.5.0.1

**其他内容**
我是今天才在群友的推荐下了解到此项目，之前未接触过Ubuntu系统，这是首次尝试部署运行，对于Config.json文件的内容不太了解(如果可以的话，我希望大佬能给此配置文件增加相应的注释说明，非常感谢)，因此Config.json为默认的配置文件，没有任何修改，此问题可能与此有一定关系。

**Comment by deng-rui** [comment]
好的 原因应该是ReadMAP的问题

**Comment by deng-rui** [comment]
配置文件增加相应的注释说明这个正在考虑
目前会准备写进doc中

**Comment by deng-rui** [comment]
你可以试试1.5.0.2
新的版本正在准备中

**Comment by EdgeStar2020** [comment]
> 你可以试试1.5.0.2
> 新的版本正在准备中

好的，辛苦大佬了
