### ISSUE TITLE
未知错误导致云服务器CPU占用率从1%提升至100%

### ISSUE THREAD

**Issue by EdgeStar2020** [deng-rui/RW-HPS#59]
**描述错误**
        昨天(4月4日)20:00左右使用命令`java -jar Server.jar &`启用了服务器，之后退出服务端把IP地址扔给了群友让他们玩去了，然后没有再管。
        截至到今天(4月5日)12:50，服务器都一直运行正常，CPU占有率维持在1%左右(注：服务器只运行了这一个jar)。
        直到12:53才出现了CPU满载的情况，这种情况持续到了16:00左右(此时我才发现)。
        稍微检查了一下，服务器为空房间，即便CPU满载也仍可以正常通过IP地址(114.55.253.162:2020)进入房间，查看了 nohup.out 最后几行的日志。
        然后直接重启了一下，问题就解决了，但不知道之后会不会再出现。
        我怀疑可能与我使用的命令`java -jar Server.jar &`或Config.json的某些配置有关，但我对这方面确实不太了解，所以来问一下(其实是想问一下大佬有没有推荐的指令)。

**截图**
![image](https://user-images.githubusercontent.com/58938653/113550897-66a5d600-9626-11eb-9dcc-8abc729e00b1.png)
![image](https://user-images.githubusercontent.com/58938653/113550911-6b6a8a00-9626-11eb-806d-4a4c32a935b2.png)
以上两图是CPU占用情况
![image](https://user-images.githubusercontent.com/58938653/113559084-5cd69f80-9633-11eb-9269-144f78dcdccd.png)
![image](https://user-images.githubusercontent.com/58938653/113560281-55b09100-9635-11eb-9b64-cf227ecc7287.png)
以上两图是nohup.out文件和 nohup.out文件最后几行的日志

**相关信息**
  -设备：阿里云服务器
  -操作系统：Ubuntu  20.04 64位
  -游戏版本：1.14h3
  -服务器版本：1.5.0.2BETA

**其他内容**
另外，我还有两个不确定是不是bug的问题想了解一下
1.  为什么之前的1.4.0.4版本已经支持断线重连，但在最新版反而无法断线重连。
![3143](https://user-images.githubusercontent.com/58938653/113555043-da4ae180-962c-11eb-8676-210613461429.jpg)
~~2. Config.json文件里的`"webUrl":"",`配置项是否就是[#49 ](https://github.com/deng-rui/RW-HPS/issues/49)里面提到的自定义URL，我昨天尝试给IP套上域名，但没有成功，猜想可能与此有关。~~（已解决）

**Comment by deng-rui** [comment]
应该是UDP导致的CPU 100% 这个bug不知道在1.5.0.*可否使用
- 目前的UDP实现是直接使用的官方版本 不是我自己写的 因为没时间
重连的话 目前是因为部分原因 暂时没有进行开源 不过我相信这一天会很快到来

解决办法
CPU 100 % 你可以在配置中关闭UDP,即true -> false

本问题将会在开源重连后关闭

2021.4.10 14:23

**Comment by deng-rui** [comment]
如果是使用命令的话 您可以在游戏中输入.help即可查看
服务端输入help也可查看

**Comment by EdgeStar2020** [comment]
> 如果是使用命令的话 您可以在游戏中输入.help即可查看
> 服务端输入help也可查看

OK，此命令我已经知晓，另外反馈一个群友发现的问题，即地图的预览图无法在玩家的房间内显示，我之前自己测试时(手机本地有预览图)忽略了这一点。
另外群里有铁锈地图作者还希望能够增加可以自己上传地图到服务器的功能(因为需要经常测试新地图)，我暂时使用的替代方案是让他们自行使用SFTP连接上传地图文件至服务器，但当前服务器对于maps文件夹内的地图似乎不支持热加载，仍然需要重启。
最后说点其他的，因为某些原因，我群里目前玩铁锈的人不是很多(群友大部分都是做地图做mod之类的，我自己也没玩在弄其他东西)，本来我弄这个是想把空闲的服务器利用起来，结果群里似乎没什么人玩的样子……所以大佬你如果有铁锈群的话，也可以让他们来玩，顺带测试一下铁锈服务器的稳定性和问题，目前IP地址是tx.byx2020.com:2020或114.55.253.162:2020，此服务器预计至少在今年国庆节之前都会一直长期开放，如果他们需要上传地图的话也可以用WinSCP来SFTP上传，用户名byxy密码2020。
![WinSCP](https://user-images.githubusercontent.com/58938653/114268281-e2db5780-9a32-11eb-97f2-ff5461c4c863.jpg)

**Comment by deng-rui** [comment]
伪重连 END
