### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by Rurityan** [deng-rui/RW-HPS#65]
内存占用随时间从2%一直升到35%才保持稳定(2G内存).

**Comment by deng-rui** [comment]
开了UDP吗?

**Comment by deng-rui** [comment]
这个版本开UDP似乎会出现泄漏  
你可以尝试启动时限制最大内存为64再看看

**Comment by Rurityan** [comment]
> 这个版本开UDP似乎会出现泄漏
> 你可以尝试启动时限制最大内存为64再看看

好的

**Comment by deng-rui** [comment]
你可以等待这两天的新版本 :D  
内部版本为1.5.0.0 :)
