### ISSUE TITLE
玩家进入房间时报错空指针异常

### ISSUE THREAD

**Issue by EdgeStar2020** [deng-rui/RW-HPS#66]
**描述错误**
今天下午刚更新到了最新版1.5.0.0 Milepost，之后发现玩家进入房间就直接掉线，初步检查应该不是配置文件的问题。

**截图**
![image](https://user-images.githubusercontent.com/58938653/118099870-67414180-b408-11eb-9c21-61e91280d0bb.png)
![2948](https://user-images.githubusercontent.com/58938653/118099933-77f1b780-b408-11eb-8483-c1358c6215da.jpg)

*请填写以下信息：**
  -操作系统：Ubuntu 20.04 64位
  -服务器版本：1.5.0.0 Milepost

**Comment by deng-rui** [comment]
已知晓，为协议上传缺失
将会周末修复:)
感谢您的反馈
