### ISSUE TITLE
项目使用jdk11在idea中无法构建

### ISSUE THREAD

**Issue by Minxyzgo** [deng-rui/RW-HPS#67]
出现`java.net.http`包不存在，`Thread.destroy`被弃用而导致无法构建的问题。我在网上查询也确实发现在jdk11中存在这些问题。所以我不知道您如何使用jdk11进行构建的，也可能是我的设置问题，是否需要将jdk版本降到jdk8?

**Comment by deng-rui** [comment]
你可以尝试在idea使用更高的jdk
我本人目前是使用的jdk15，你可以尝试，或者去掉~/net/HTTPCil~.java中使用java11的HTTP的参数
不能替换到j8，因为使用了j9的getpid参数（可以去掉后用j8）

**Comment by Minxyzgo** [comment]
> 你可以尝试在idea使用更高的jdk
> 我本人目前是使用的jdk15，你可以尝试，或者去掉~/net/HTTPCil~.java中使用java11的HTTP的参数
> 不能替换到j8，因为使用了j9的getpid参数（可以去掉后用j8）

切换到jdk15后，可以构建运行了，十分感谢。
